// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace PlanVest.Api.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

        modelBuilder.Entity("PlanVest.Api.Models.ApplicationUser", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            entity.Property<string>("DisplayName").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
            entity.Property<string>("Email").IsRequired().HasMaxLength(254).HasColumnType("TEXT");
            entity.Property<bool>("IsDemo").HasColumnType("INTEGER");
            entity.Property<DateTimeOffset?>("LastLoginAt").HasColumnType("TEXT");
            entity.Property<string>("NormalizedEmail").IsRequired().HasMaxLength(254).HasColumnType("TEXT");
            entity.Property<string>("PasswordHash").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
            entity.Property<int>("TokenVersion").HasColumnType("INTEGER");
            entity.HasKey("Id");
            entity.HasIndex("NormalizedEmail").IsUnique();
            entity.ToTable("Users");
        });

        modelBuilder.Entity("PlanVest.Api.Models.FinancialGoal", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            entity.Property<decimal>("AssumedAnnualReturn").HasPrecision(5, 2).HasColumnType("TEXT");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            entity.Property<decimal>("CurrentAmount").HasPrecision(18, 2).HasColumnType("TEXT");
            entity.Property<string>("GoalType").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            entity.Property<decimal>("MonthlyContribution").HasPrecision(18, 2).HasColumnType("TEXT");
            entity.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            entity.Property<string>("Status").IsRequired().HasMaxLength(24).HasColumnType("TEXT");
            entity.Property<decimal>("TargetAmount").HasPrecision(18, 2).HasColumnType("TEXT");
            entity.Property<DateOnly>("TargetDate").HasColumnType("TEXT");
            entity.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
            entity.Property<Guid>("UserId").HasColumnType("TEXT");
            entity.HasKey("Id");
            entity.HasIndex("UserId");
            entity.ToTable("FinancialGoals");
        });

        modelBuilder.Entity("PlanVest.Api.Models.Holding", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            entity.Property<string>("AssetClass").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            entity.Property<string>("AssetName").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
            entity.Property<decimal>("AverageCost").HasPrecision(18, 2).HasColumnType("TEXT");
            entity.Property<decimal>("CurrentPrice").HasPrecision(18, 2).HasColumnType("TEXT");
            entity.Property<Guid>("InvestmentAccountId").HasColumnType("TEXT");
            entity.Property<decimal>("Quantity").HasPrecision(18, 6).HasColumnType("TEXT");
            entity.Property<string>("Symbol").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            entity.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
            entity.HasKey("Id");
            entity.HasIndex("InvestmentAccountId");
            entity.ToTable("Holdings");
        });

        modelBuilder.Entity("PlanVest.Api.Models.InvestmentAccount", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            entity.Property<string>("AccountType").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            entity.Property<string>("BaseCurrency").IsRequired().HasMaxLength(3).HasColumnType("TEXT");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            entity.Property<string>("Name").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
            entity.Property<Guid>("UserId").HasColumnType("TEXT");
            entity.HasKey("Id");
            entity.HasIndex("UserId");
            entity.ToTable("InvestmentAccounts");
        });

        modelBuilder.Entity("PlanVest.Api.Models.PortfolioTransaction", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            entity.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("TEXT");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            entity.Property<Guid?>("HoldingId").HasColumnType("TEXT");
            entity.Property<Guid>("InvestmentAccountId").HasColumnType("TEXT");
            entity.Property<string>("Note").HasMaxLength(240).HasColumnType("TEXT");
            entity.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("TEXT");
            entity.Property<decimal>("Quantity").HasPrecision(18, 6).HasColumnType("TEXT");
            entity.Property<DateOnly>("TransactionDate").HasColumnType("TEXT");
            entity.Property<string>("Type").IsRequired().HasMaxLength(24).HasColumnType("TEXT");
            entity.HasKey("Id");
            entity.HasIndex("HoldingId");
            entity.HasIndex("InvestmentAccountId");
            entity.ToTable("Transactions");
        });

        modelBuilder.Entity("PlanVest.Api.Models.RiskAssessment", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            entity.Property<string>("AnswersJson").IsRequired().HasColumnType("TEXT");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            entity.Property<string>("Rationale").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
            entity.Property<string>("RiskProfile").IsRequired().HasMaxLength(24).HasColumnType("TEXT");
            entity.Property<string>("ScoringVersion").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
            entity.Property<int>("TotalScore").HasColumnType("INTEGER");
            entity.Property<Guid>("UserId").HasColumnType("TEXT");
            entity.HasKey("Id");
            entity.HasIndex("UserId", "CreatedAt");
            entity.ToTable("RiskAssessments");
        });

        modelBuilder.Entity("PlanVest.Api.Models.FinancialGoal", entity =>
        {
            entity.HasOne("PlanVest.Api.Models.ApplicationUser", null)
                .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("PlanVest.Api.Models.Holding", entity =>
        {
            entity.HasOne("PlanVest.Api.Models.InvestmentAccount", "InvestmentAccount")
                .WithMany("Holdings").HasForeignKey("InvestmentAccountId")
                .OnDelete(DeleteBehavior.Cascade).IsRequired();
            entity.Navigation("InvestmentAccount");
        });

        modelBuilder.Entity("PlanVest.Api.Models.InvestmentAccount", entity =>
        {
            entity.HasOne("PlanVest.Api.Models.ApplicationUser", null)
                .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("PlanVest.Api.Models.PortfolioTransaction", entity =>
        {
            entity.HasOne("PlanVest.Api.Models.Holding", "Holding")
                .WithMany().HasForeignKey("HoldingId").OnDelete(DeleteBehavior.SetNull);
            entity.HasOne("PlanVest.Api.Models.InvestmentAccount", "InvestmentAccount")
                .WithMany("Transactions").HasForeignKey("InvestmentAccountId")
                .OnDelete(DeleteBehavior.Cascade).IsRequired();
            entity.Navigation("Holding");
            entity.Navigation("InvestmentAccount");
        });

        modelBuilder.Entity("PlanVest.Api.Models.RiskAssessment", entity =>
        {
            entity.HasOne("PlanVest.Api.Models.ApplicationUser", null)
                .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("PlanVest.Api.Models.InvestmentAccount", entity =>
        {
            entity.Navigation("Holdings");
            entity.Navigation("Transactions");
        });
#pragma warning restore 612, 618
    }
}
